/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package one.app.desktop.internal;

import one.client.jre.OneJre;
import one.common.One;
import one.core.dsl.CoreDsl;
import one.core.dsl.callbacks.WhenLoaded;
import one.core.dsl.callbacks.WhenShutdown;
import one.core.dsl.callbacks.results.WithLoadResult;
import one.core.nodes.OneTypedReference;
import one.core.nodes.OneValue;

/**
 *
 * @author mroh004
 */
public class UploadTextForm extends javax.swing.JPanel {

    /**
     * Creates new form UploadTextForm
     */
    public UploadTextForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        uploadText_toNode = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        uploadText_secret = new javax.swing.JTextField();
        uploadText_public = new javax.swing.JCheckBox();
        uploadText_asValue = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        uploadText_text = new javax.swing.JTextArea();
        uploadText_button = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        uploadText_name = new javax.swing.JTextField();

        jLabel3.setText("to Node:");

        jLabel4.setText("Secret:");

        uploadText_public.setText("public");
        uploadText_public.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadText_publicActionPerformed(evt);
            }
        });

        uploadText_asValue.setText("as value");
        uploadText_asValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadText_asValueActionPerformed(evt);
            }
        });

        jLabel5.setText("Text");

        uploadText_text.setColumns(20);
        uploadText_text.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        uploadText_text.setRows(5);
        jScrollPane2.setViewportView(uploadText_text);

        uploadText_button.setText("Upload");
        uploadText_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadText_buttonActionPerformed(evt);
            }
        });

        jLabel6.setText("Name");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(uploadText_button))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(uploadText_secret)
                                    .addComponent(uploadText_toNode))))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(uploadText_public)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uploadText_asValue)
                                .addGap(66, 66, 66)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uploadText_name, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 10, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(uploadText_toNode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(uploadText_secret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uploadText_public)
                    .addComponent(uploadText_asValue)
                    .addComponent(jLabel6)
                    .addComponent(uploadText_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(uploadText_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void uploadText_publicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadText_publicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uploadText_publicActionPerformed

    private void uploadText_asValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadText_asValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uploadText_asValueActionPerformed

    private void uploadText_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadText_buttonActionPerformed


        final CoreDsl dsl = OneJre.init("<no api key>");
        
        final OneTypedReference<?> ref = One.reference(uploadText_toNode.getText());

        final String secret = uploadText_secret.getText();

        final boolean asValue = uploadText_asValue.isSelected();

        final boolean isPublic = uploadText_public.isSelected();
        
        uploadText_button.setEnabled(false);

        dsl.load(ref).withSecret(secret).and(new WhenLoaded() {

            @Override
            public void thenDo(WithLoadResult<Object> wlr) {


                if (!asValue) {
                    dsl.append(uploadText_text.getText()).to(wlr.loadedNode()).in(wlr.client());
                    
                } else {
                    OneValue<?> appended =dsl.append(uploadText_text.getText()).to(wlr.loadedNode()).atAddress("./" + uploadText_name.getText()).in(wlr.client());
                    dsl.append(dsl.reference("https://admin1.linnk.it/types/v01/isHtmlValue")).to(appended).in(wlr.client());
                }

                if (isPublic) {
                    dsl.append(dsl.newNode().asPublicReadToken()).to(wlr.loadedNode()).in(wlr.client());
                }
                
                dsl.shutdown(wlr.client()).and(new WhenShutdown() {

                    @Override
                    public void thenDo() {
                        uploadText_button.setEnabled(true);
                    }
                });

            }
        });

    }//GEN-LAST:event_uploadText_buttonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox uploadText_asValue;
    private javax.swing.JButton uploadText_button;
    private javax.swing.JTextField uploadText_name;
    private javax.swing.JCheckBox uploadText_public;
    private javax.swing.JTextField uploadText_secret;
    private javax.swing.JTextArea uploadText_text;
    private javax.swing.JTextField uploadText_toNode;
    // End of variables declaration//GEN-END:variables
}
